name: Deploy Vue 3 with Docker

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 获取 Git 提交哈希
      - name: Get Git commit hash
        id: git-hash
        run: echo "GIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # 3. 设置 Docker：登录阿里云镜像仓库
      - name: Log in to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com

      # 4. 构建并推送 Docker 镜像到阿里云
      - name: Build and push Docker image
        env:
          REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}
          IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
          TAG: ${{ github.ref_name }}-${{ env.GIT_HASH }}
        run: |
          docker build -t $REGISTRY/$NAMESPACE/$IMAGE_NAME:$TAG .
          docker push $REGISTRY/$NAMESPACE/$IMAGE_NAME:$TAG

      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
      #       cd /root/wallApi
      #       docker-compose pull
      #       docker-compose up -d
